### ISSUE TITLE
Can you explain the role of self.prior_z_logD, it seems to be useless

### ISSUE THREAD

**Issue by Zyazz** [zhuchen03/VIBNet#2]
Does it have any other effect?

**Comment by Zyazz** [comment]
And why init_mag default value is 9

**Comment by zhuchen03** [comment]
What do you mean by useless? Can you give some more specific descriptions?

**Comment by zhuchen03** [comment]
Oh I got it. You are correct, it is not used in the current version of code. Please disregard it.

**Comment by Zyazz** [comment]
> Oh I got it. You are correct, it is not used in the current version of code. Please disregard it.

thank you !
