### ISSUE TITLE
running crash on CPU

### ISSUE THREAD

**Issue by ZexinLi0w0** [zhuchen03/VIBNet#9]
Thanks to the author for posting this very easy-to-read code.

When conducting testing, I recognize there is a compatible bug preventing running on the CPU end.
In Line 17 in `ib_layers.py` of function `reparameterize`
```
eps = torch.FloatTensor(batch_size, std.size(0)).cuda(mu.get_device()).normal_()
```
Here if the model is located on the CPU, then `mu.get_device()` will return `-1`. Then `torch.FloatTensor(...).cuda(-1)` will raise an runtime error like following:
```
RuntimeError: Device index must not be negative
```
I suggest the author make conditional statements here to avoid runtime error.

**Comment by zhuchen03** [comment]
Thanks for pointing this out! Indeed the code version might be a bit outdated. Please feel free to submit a pull request to recognize your contribution to the repo, or I can also submit the change later.
